version: '3'

services:

  openmu-startup:
    build:
      context: ../../src
      dockerfile: Startup/Dockerfile
    restart: "no"
    environment:
      # Para pruebas en red local, anunciar IP local a los clientes.
      # Cambiar a "public" si van a conectarse desde Internet.
      RESOLVE_IP: local
    ports:
      - "8081:8080"

  database:
    ports:
      - "5433:5432"
